import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show SynchronousFuture;

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('es'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'initialSetupTitle': 'Configuración Inicial del Negocio',
      'initialSetupWelcome': '¡Bienvenido! Completa los datos de tu negocio para comenzar.',
      'settingsTitle': 'Configuración de la Empresa',
      'home': 'Inicio',
      'appName': 'Seller',
      'save': 'Guardar',
      'companyLogo': 'Logo de la Empresa',
      'uploadLogo': 'Subir Logo',
      'deleteLogo': 'Eliminar Logo',
      'confirmDeleteLogo': '¿Estás seguro de que quieres eliminar el logo?',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'logoUpdated': 'Logo actualizado con éxito.',
      'errorUpload': 'Error al subir el logo: ',
      'logoDeleted': 'Logo eliminado.',
      'error': 'Error: ',
      'settingsSaved': 'Configuración guardada.',
      'total': 'Total',
      'noMovements': 'Sin movimientos',
      'companyName': 'Nombre de la Empresa',
      'enterName': 'Introduce un nombre',
      'companyAddress': 'Dirección de la Empresa',
      'companyPhone': 'Teléfono de la Empresa',
      'vatRate': 'Tasa de IVA (%)',
      'vatRateHint': 'Ej: 19.0',
      'profitMarginHint': 'Ej: 30.0',
      'decimalPlacesHint': 'Ej: 0 o 2',
      'decimalPlaces': 'Número de Decimales',
      'enterValidNumber': 'Introduce un número válido',
      'profitMargin': 'Margen de Utilidad (%)',
      'welcome': 'Bienvenido',
      'todaySales': 'Ventas Hoy',
      'monthlySales': 'Ventas del Mes',
      'recentSales': 'Ventas Recientes',
      'totalDebt': 'Deuda Total Clientes',
      'lowStock': 'Productos Bajo Stock',
      'quickActions': 'Acciones Rápidas',
      'sellers': 'Vendedores',
      'suppliers': 'Proveedores',
      'customers': 'Clientes',
      'products': 'Productos',
      'stock': 'Stock',
      'offers': 'Ofertas',
      'sales': 'Ventas',
      'payments': 'Pagos',
      'reports': 'Reportes e informes',
      'newSale': 'Nueva Venta',
      'logout': 'Cerrar Sesión',
      'admin': 'Administrador',
      'seller': 'Vendedor',
      'about': 'Acerca de',
      'version': 'Versión',
      'systemDescription': 'Sistema de gestión de ventas, inventario y clientes.',
      'salesAndPaymentsReport': 'Informe de Ventas y Pagos',
      'financialSummary': 'Resumen Financiero',
      'totalPayments': 'Total Pagos',
      'close': 'Cerrar',
      'salesSummary': 'Resumen de Ventas',
      'salesByProduct': 'Ventas por Producto',
      'customerRanking': 'Ranking de Clientes',
      'accountsReceivable': 'Cuentas por Cobrar',
      'stockReport': 'Informe de Stock',
      'language': 'Idioma',
      'cashFlow': 'Flujo de Caja',
      'sellerPerformance': 'Rendimiento Vendedores',
      'categories': 'Categorías',
      'addCategory': 'Añadir Categoría',
      'editCategory': 'Editar Categoría',
      'categoryName': 'Nombre de la categoría',
      'categoryExists': 'Ya existe una categoría con este nombre.',
      'categoryDeleted': 'Categoría eliminada',
      'errorDelete': 'Error al eliminar: ',
      'cannotDeleteCategory': 'Esta categoría está asignada a uno o más productos y no puede ser eliminada.',
      'confirmDeleteCategory': '¿Seguro que quieres eliminar esta categoría?',
      'noCategories': 'No hay categorías. ¡Añade una!',
      'searchCustomer': 'Buscar cliente por nombre o DNI',
      'noProducts': 'No hay productos. ¡Añade uno!',
      'searchProductHint': 'Buscar producto por nombre o código',
      'filterSeller': 'Filtrar por vendedor',
      'allSellers': 'Todos los vendedores',
      'filterCity': 'Filtrar por ciudad',
      'allCities': 'Todas las ciudades',
      'noCustomers': 'No se encontraron clientes',
      'noCustomersAdd': 'No hay clientes. ¡Añade uno!',
      'name': 'Nombre',
      'customerName': 'Nombre del Cliente',
      'required': 'Requerido',
      'dni': 'DNI/CIF',
      'contactPerson': 'Persona de Contacto',
      'phone': 'Teléfono',
      'email': 'Email',
      'validEmail': 'Por favor, introduce un email válido.',
      'address': 'Dirección',
      'city': 'Ciudad',
      'assignSeller': 'Asignar Vendedor',
      'adminUnassigned': 'Administrador / Sin asignar',
      'sellerNotExist': 'Vendedor no existe (reasignar)',
      'customerExists': 'Ya existe un cliente con este nombre.',
      'customerDeleted': 'Cliente eliminado',
      'cannotDeleteCustomer': 'Este cliente no se puede eliminar porque tiene ventas asociadas.',
      'confirmDeleteCustomer': '¿Seguro que quieres eliminar este cliente?',
      'createdBy': 'Creado por: ',
      'addCustomer': 'Añadir Cliente',
      'editCustomer': 'Editar Cliente',
      'editPayment': 'Editar Pago',
      'productsCount': 'Productos: ',
      'settings': 'Configuración',
      'selectProfile': 'Seleccionar Perfil',
      'unknownProfile': 'Perfil Desconocido',
      'role': 'Rol',
      'unknownRole': 'desconocido',
      'user': 'usuario',
      'createBusinessHello': 'Hola, {userName}!',
      'createBusinessMessage': 'Parece que eres nuevo aquí. Puedes crear tu propio negocio para empezar a gestionar tu catálogo, o esperar a que un administrador te añada como vendedor a su negocio.',
      'createOwnBusiness': 'Crear Mi Propio Negocio',
      'createBusinessInfo': 'Si ya has sido añadido como vendedor, por favor, cierra sesión y vuelve a entrar para que se actualicen tus perfiles.',
      'errorCreatingBusiness': 'Error al crear el negocio: {error}',
      'loadingProfilesError': 'Error al cargar perfiles: {error}',
      'selectLanguage': 'Seleccionar Idioma',
      'salesVsPaymentsMonthly': 'Ventas vs Pagos (Mensual)',
      'lowStockProductsTitle': 'Productos con Bajo Stock',
      'commonTasksTitle': 'Tareas Comunes',
      'allStockInOrder': 'Todo el stock está en orden.',
      'stockValue': 'Stock: {value}',
      'noName': 'Sin nombre',
      'noEmail': 'Sin email',
      'manageSellers': 'Gestión de Vendedores',
      'editSeller': 'Editar Vendedor',
      'newSeller': 'Nuevo Vendedor',
      'searchSellerHint': 'Buscar vendedor por nombre o email',
      'noSellersFound': 'No se encontraron vendedores.',
      'deleteSeller': 'Eliminar Vendedor',
      'deleteSellerConfirmation': 'Este vendedor tiene {customerCount} clientes asignados. Se reasignarán automáticamente a ti (Administrador) y el vendedor será eliminado. ¿Continuar?',
      'deleteSellerConfirmationSimple': '¿Estás seguro de que quieres eliminar a este vendedor? Perderá el acceso inmediatamente.',
      'sellerDeleted': 'Vendedor eliminado y clientes reasignados',
      'sellerUpdated': 'Vendedor actualizado',
      'sellerAdded': 'Vendedor añadido',
      'emailHint': 'Email (Cuenta Google)',
      'sellerAccessInfo': 'Este usuario podrá acceder a tu base de datos con permisos limitados (solo verá sus ventas y clientes).',
      'continueAction': 'Continuar',
      'invalidEmail': 'Email inválido',
      'sellerTag': 'Vendedor',
      'noPaymentsFound': 'No se encontraron pagos.',
      'paymentOf': 'Pago de',
      'date': 'Fecha',
      'stockManagement': 'Gestión de Stock',
      'searchProduct': 'Buscar producto',
      'scanBarcode': 'Escanear código de barras',
      'filterProducts': 'Filtrar productos',
      'selectSupplier': 'Seleccionar Proveedor',
      'saleNumber': 'Venta N°',
      'bySupplier': 'Por Proveedor',
      'viewAll': 'Ver Todos',
      'addStockTo': 'Agregar Stock: {productName}',
      'currentStockIs': 'Stock actual: {stock}',
      'amountToAdd': 'Cantidad a agregar',
      'negativeToSubtract': 'Usa números negativos para restar',
      'stockUpdated': 'Se agregaron {amount} unidades al stock',
      'noProductsFound': 'No se encontraron productos.',
      'updateStock': 'Actualizar Stock',
      'stockInUnits': 'Stock actual: {stock} unidades',
      'inBoxes': ' ({boxes} cajas)',
      'searchSupplierHint': 'Buscar proveedor',
      'addSupplier': 'Añadir Proveedor',
      'editSupplier': 'Editar Proveedor',
      'noSuppliersFound': 'No se encontraron proveedores.',
      'confirmDelete': 'Confirmar Eliminación',
      'confirmDeleteSupplier': '¿Seguro que quieres eliminar este proveedor?',
      'totalSales': 'Total Ventas',
      'transactions': 'transacciones',
      'noSalesInPeriod': 'No hay ventas en este período.',
      'purchases': 'compras',
      'allUpToDate': '¡Todo al día!',
      'noPendingDebts': 'No hay cuentas por cobrar pendientes.',
      'totalPendingCollection': 'Total Pendiente de Cobro',
      'salesWithDebt': 'ventas con deuda',
      'costValue': 'Valor Costo',
      'saleValue': 'Valor Venta',
      'low': 'Bajo',
      'search': 'Buscar',
      'allProducts': 'Todos los productos',
      'selectProduct': 'Seleccionar Producto',
      'selectCustomer': 'Seleccionar Cliente',
      'allCustomers': 'Todos los clientes',
      'productLabel': 'Producto: ',
      'customerLabel': 'Cliente: ',
      'sellerLabel': 'Vendedor: ',
      'all': 'Todos',
      'paymentMethod': 'Método de Pago',
      'cash': 'Efectivo',
      'bank': 'Banco',
      'newPayment': 'Nuevo Pago',
      'continueToPay': 'Continuar a Pagar',
      'payAnotherAmount': 'Pagar Otro Monto',
      'salesCountLabel': 'ventas',
      'confirmDeletePayment': '¿Seguro que quieres eliminar este pago?',
      'paymentDeleted': 'Pago eliminado',
      'selectPaymentMode': 'Seleccionar Modo de Pago',
      'paySpecificSales': 'Pagar ventas específicas',
      'payOnAccount': 'Abonar cuenta total',//dsfsdfsf
      'totalPending': 'Total Pendiente',
      'amountToPay': 'Monto a Pagar',
      'filter': 'Filtrar',
      'ungrouped': 'Sin agrupar',
      'groupByCategory': 'Agrupar por Categoría',
      'groupBySupplier': 'Agrupar por Proveedor',
      'filterByCategory': 'Filtrar por Categoría',
      'filterBySupplier': 'Filtrar por Proveedor',
      'category': 'Categoría',
      'supplier': 'Proveedor',
      'no': 'Sin',
      'selectCategory': 'Seleccionar Categoría',
      'addProduct': 'Añadir Producto',
      'editProduct': 'Editar Producto',
      'selectSeller': 'Seleccionar Vendedor',
      'filterBySeller': 'Filtrar por Vendedor',
      'selectDateRange': 'Seleccionar Fechas',
      'filterToday': 'Hoy',
      'filterThisWeek': 'Esta Semana',
      'filterWeek': 'Semana',
      'filterThisMonth': 'Este Mes',
      'filterMonth': 'Mes',
      'filterThisYear': 'Este Año',
      'filterYear': 'Año',
      'filterAll': 'Todo',
      'filterCustom': 'Personalizado',
      'filterCustomEllipsis': 'Personalizado...',
      'noCustomer': 'Sin cliente',
      'printList': 'Imprimir Lista',
      'printOffersCatalog': 'Imprimir Catálogo de Ofertas',
      'noProductsToPrint': 'No hay productos en la lista actual para imprimir.',
      'noOfferProductsToPrint': 'No se encontraron productos con ofertas activas.',
      'noOffers': 'No hay ofertas registradas.',
      'productHeader': 'Producto',
      'quantityHeader': 'Cant.',
      'totalHeader': 'Total',
      'unitsPerBox': '({count} un x cj.)',
      'productState': 'Estado del Producto',
      'description': 'Descripción',
      'barCode': 'Código de Barras',
      'unitsBox': 'Unidades por Caja',
      'purchasePrice': 'Precio Compra',
      'vatIncluded': 'IVA Incluido',
      'margin': 'Margen',
      'salePrice': 'Precio Venta',
      'currentStock': 'Stock Actual',
      'safetyStock': 'Stock de Seguridad',
      'offersActive': 'Ofertas Activas',
      'createOffer': 'Crear Oferta',
      'password': 'Contraseña',
      'signIn': 'Iniciar Sesión',
      'signUp': 'Registrarse',
      'noAccount': '¿No tienes cuenta? Crea una',
      'haveAccount': '¿Ya tienes cuenta? Ingresa',
      'or': 'o',
      'forgotPassword': '¿Olvidaste tu contraseña?',
      'resetEmailSent': 'Se ha enviado un correo para restablecer tu contraseña a {email}',
      'sellerUnknown': 'Desconocido',
      'saleNumberSN': 'N° venta : S/N',
      'customerSearchHint': 'Escribe para buscar...',
      'selectCustomerError': 'Debes seleccionar un cliente.',
      'netLabel': 'Neto',
      'vatLabel': 'IVA',
      'paidLabel': 'Pagado',
      'balanceLabel': 'Saldo',
      'recordedPayments': 'Pagos Registrados:',
      'loadingPayments': 'Cargando pagos...',
      'paymentLabel': 'Pago',
      'noteOptional': 'Nota (Opcional)',
      'addOneProductError': 'Debes añadir al menos un producto.',
      'saleSavedSuccess': 'Venta y pago guardados con éxito',
      'saleUpdatedSuccess': 'Venta actualizada con éxito',
      'saleAlreadyPaid': 'Esta venta ya está pagada.',
      'deleteOfferConfirm': '¿Estás seguro de eliminar esta oferta?',
      'saveWithoutPayment': 'Guardar sin Pago',
      'noSales': 'No hay ventas recientes.',
      'addNewCustomer': 'Añadir nuevo cliente',
      'createNewProduct': 'Crear nuevo producto',
      'regularPrice': 'Precio Normal',
      'takingMinQty': 'Llevando {qty} o más',
      'offersForProduct': 'Ofertas para "{product}"',
      'quantityLabel': 'Cantidad',
      'salePriceIvaInc': 'Precio Unitario (IVA inc.)',
      'salePriceNet': 'Precio Unitario (Neto)',
      'priceIncludesVat': 'El precio incluye IVA',
      'totalIvaInc': 'Total (IVA inc.)',
      'of': 'de',
      'saleDeletedSuccess': 'Venta eliminada con éxito',
      'noSalesRegistered': 'No hay ventas registradas.',
      'confirmDeleteSale': '¿Estás seguro de que quieres eliminar esta venta? Esta acción no se puede deshacer.',
    },
    'en': {
      'initialSetupTitle': 'Initial Business Setup',
      'initialSetupWelcome': 'Welcome! Complete your business details to get started.',
      'settingsTitle': 'Company Settings',
      'home': 'Home',
      'appName': 'Seller',
      'save': 'Save',
      'companyLogo': 'Company Logo',
      'uploadLogo': 'Upload Logo',
      'deleteLogo': 'Delete Logo',
      'confirmDeleteLogo': 'Are you sure you want to delete the logo?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'logoUpdated': 'Logo updated successfully.',
      'errorUpload': 'Error uploading logo: ',
      'logoDeleted': 'Logo deleted.',
      'error': 'Error: ',
      'settingsSaved': 'Settings saved.',
      'total': 'Total',
      'noMovements': 'No movements',
      'companyName': 'Company Name',
      'enterName': 'Enter a name',
      'companyAddress': 'Company Address',
      'companyPhone': 'Company Phone',
      'vatRate': 'VAT Rate (%)',
      'vatRateHint': 'e.g. 21.0',
      'profitMarginHint': 'e.g. 30.0',
      'decimalPlacesHint': 'e.g. 0 or 2',
      'decimalPlaces': 'Decimal Places',
      'enterValidNumber': 'Enter a valid number',
      'profitMargin': 'Profit Margin (%)',
      'welcome': 'Welcome',
      'todaySales': 'Today\'s Sales',
      'monthlySales': 'Monthly Sales',
      'recentSales': 'Recent Sales',
      'totalDebt': 'Total Customer Debt',
      'lowStock': 'Low Stock Products',
      'quickActions': 'Quick Actions',
      'sellers': 'Sellers',
      'suppliers': 'Suppliers',
      'customers': 'Customers',
      'products': 'Products',
      'stock': 'Stock',
      'offers': 'Offers',
      'sales': 'Sales',
      'payments': 'Payments',
      'reports': 'Reports',
      'newSale': 'New Sale',
      'logout': 'Logout',
      'admin': 'Administrator',
      'user': 'user',
      'seller': 'Seller',
      'about': 'About',
      'version': 'Version',
      'systemDescription': 'Sales, inventory, and customer management system.',
      'salesAndPaymentsReport': 'Sales and Payments Report',
      'financialSummary': 'Financial Summary',
      'totalPayments': 'Total Payments',
      'close': 'Close',
      'salesSummary': 'Sales Summary',
      'salesByProduct': 'Sales by Product',
      'customerRanking': 'Customer Ranking',
      'accountsReceivable': 'Accounts Receivable',
      'stockReport': 'Stock Report',
      'language': 'Language',
      'cashFlow': 'Cash Flow',
      'sellerPerformance': 'Seller Performance',
      'categories': 'Categories',
      'addCategory': 'Add Category',
      'editCategory': 'Edit Category',
      'categoryName': 'Category Name',
      'categoryExists': 'A category with this name already exists.',
      'categoryDeleted': 'Category deleted',
      'errorDelete': 'Error deleting: ',
      'cannotDeleteCategory': 'This category is assigned to one or more products and cannot be deleted.',
      'confirmDeleteCategory': 'Are you sure you want to delete this category?',
      'noCategories': 'No categories. Add one!',
      'searchCustomer': 'Search customer by name or ID',
      'noProducts': 'No products. Add one!',
      'searchProductHint': 'Search product by name or code',
      'filterSeller': 'Filter by seller',
      'allSellers': 'All sellers',
      'filterCity': 'Filter by city',
      'allCities': 'All cities',
      'noCustomers': 'No customers found',
      'noCustomersAdd': 'No customers. Add one!',
      'name': 'Name',
      'customerName': 'Customer Name',
      'required': 'Required',
      'dni': 'ID/Tax ID',
      'contactPerson': 'Contact Person',
      'phone': 'Phone',
      'email': 'Email',
      'validEmail': 'Please enter a valid email.',
      'address': 'Address',
      'city': 'City',
      'assignSeller': 'Assign Seller',
      'adminUnassigned': 'Administrator / Unassigned',
      'sellerNotExist': 'Seller does not exist (reassign)',
      'customerExists': 'A customer with this name already exists.',
      'customerDeleted': 'Customer deleted',
      'cannotDeleteCustomer': 'This customer cannot be deleted because they have associated sales.',
      'confirmDeleteCustomer': 'Are you sure you want to delete this customer?',
      'createdBy': 'Created by: ',
      'addCustomer': 'Add Customer',
      'editCustomer': 'Edit Customer',
      'editPayment': 'Edit Payment',
      'productsCount': 'Products: ',
      'settings': 'Settings',
      'selectProfile': 'Select Profile',
      'unknownProfile': 'Unknown Profile',
      'role': 'Role',
      'unknownRole': 'unknown',
      'createBusinessHello': 'Hello, {userName}!',
      'createBusinessMessage': 'It seems you are new here. You can create your own business to start managing your catalog, or wait for an administrator to add you as a seller to their business.',
      'createOwnBusiness': 'Create My Own Business',
      'createBusinessInfo': 'If you have already been added as a seller, please log out and log back in to update your profiles.',
      'errorCreatingBusiness': 'Error creating business: {error}',
      'loadingProfilesError': 'Error loading profiles: {error}',
      'selectLanguage': 'Select Language',
      'salesVsPaymentsMonthly': 'Sales vs Payments (Monthly)',
      'lowStockProductsTitle': 'Low Stock Products',
      'commonTasksTitle': 'Common Tasks',
      'allStockInOrder': 'All stock is in order.',
      'stockValue': 'Stock: {value}',
      'noName': 'No name',
      'noEmail': 'No email',
      'manageSellers': 'Manage Sellers',
      'editSeller': 'Edit Seller',
      'newSeller': 'New Seller',
      'searchSellerHint': 'Search seller by name or email',
      'noSellersFound': 'No sellers found.',
      'deleteSeller': 'Delete Seller',
      'deleteSellerConfirmation': 'This seller has {customerCount} assigned customers. They will be automatically reassigned to you (Administrator) and the seller will be deleted. Continue?',
      'deleteSellerConfirmationSimple': 'Are you sure you want to delete this seller? They will lose access immediately.',
      'sellerDeleted': 'Seller deleted and customers reassigned',
      'sellerUpdated': 'Seller updated',
      'sellerAdded': 'Seller added',
      'emailHint': 'Email (Google Account)',
      'sellerAccessInfo': 'This user will be able to access your database with limited permissions (they will only see their sales and customers).',
      'continueAction': 'Continue',
      'invalidEmail': 'Invalid email',
      'sellerTag': 'Seller',
      'noPaymentsFound': 'No payments found.',
      'paymentOf': 'Payment of',
      'date': 'Date',
      'stockManagement': 'Stock Management',
      'searchProduct': 'Search product',
      'scanBarcode': 'Scan barcode',
      'filterProducts': 'Filter products',
      'selectSupplier': 'Select Supplier',
      'saleNumber': 'Sale #',
      'bySupplier': 'By Supplier',
      'viewAll': 'View All',
      'addStockTo': 'Add Stock: {productName}',
      'currentStockIs': 'Current stock: {stock}',
      'amountToAdd': 'Amount to add',
      'negativeToSubtract': 'Use negative numbers to subtract',
      'stockUpdated': '{amount} units added to stock',
      'noProductsFound': 'No products found.',
      'updateStock': 'Update Stock',
      'stockInUnits': 'Current stock: {stock} units',
      'inBoxes': ' ({boxes} boxes)',
      'searchSupplierHint': 'Search supplier',
      'addSupplier': 'Add Supplier',
      'editSupplier': 'Edit Supplier',
      'noSuppliersFound': 'No suppliers found.',
      'confirmDelete': 'Confirm Deletion',
      'confirmDeleteSupplier': 'Are you sure you want to delete this supplier?',
      'totalSales': 'Total Sales',
      'transactions': 'transactions',
      'noSalesInPeriod': 'No sales in this period.',
      'purchases': 'purchases',
      'allUpToDate': 'All up to date!',
      'noPendingDebts': 'No pending accounts receivable.',
      'totalPendingCollection': 'Total Pending Collection',
      'salesWithDebt': 'sales with debt',
      'costValue': 'Cost Value',
      'saleValue': 'Sale Value',
      'low': 'Low',
      'search': 'Search',
      'allProducts': 'All products',
      'selectProduct': 'Select Product',
      'selectCustomer': 'Select Customer',
      'allCustomers': 'All customers',
      'productLabel': 'Product: ',
      'customerLabel': 'Customer: ',
      'sellerLabel': 'Seller: ',
      'all': 'All',
      'paymentMethod': 'Payment Method',
      'cash': 'Cash',
      'bank': 'Bank',
      'newPayment': 'New Payment',
      'continueToPay': 'Continue to Pay',
      'payAnotherAmount': 'Pay Other Amount',
      'salesCountLabel': 'sales',
      'confirmDeletePayment': 'Are you sure you want to delete this payment?',
      'paymentDeleted': 'Payment deleted',
      'selectPaymentMode': 'Select Payment Mode',
      'paySpecificSales': 'Pay specific sales',
      'payOnAccount': 'Pay total account',//fgdg
      'totalPending': 'Total Pending',
      'amountToPay': 'Amount to Pay',
      'filter': 'Filter',
      'ungrouped': 'Ungrouped',
      'groupByCategory': 'Group by Category',
      'groupBySupplier': 'Group by Supplier',
      'filterByCategory': 'Filter by Category',
      'filterBySupplier': 'Filter by Supplier',
      'category': 'Category',
      'supplier': 'Supplier',
      'no': 'No',
      'selectCategory': 'Select Category',
      'addProduct': 'Add Product',
      'editProduct': 'Edit Product',
      'selectSeller': 'Select Seller',
      'filterBySeller': 'Filter by Seller',
      'selectDateRange': 'Select Dates',
      'filterToday': 'Today',
      'filterThisWeek': 'This Week',
      'filterWeek': 'Week',
      'filterThisMonth': 'This Month',
      'filterMonth': 'Month',
      'filterThisYear': 'This Year',
      'filterYear': 'Year',
      'filterAll': 'All',
      'filterCustom': 'Custom',
      'filterCustomEllipsis': 'Custom...',
      'noCustomer': 'No customer',
      'printList': 'Print List',
      'printOffersCatalog': 'Print Offers Catalog',
      'noProductsToPrint': 'No products in the current list to print.',
      'noOfferProductsToPrint': 'No products with active offers found.',
      'noOffers': 'No active offers.',
      'productHeader': 'Product',
      'quantityHeader': 'Qty',
      'totalHeader': 'Total',
      'unitsPerBox': '({count} un x box)',
      'productState': 'Product State',
      'description': 'Description',
      'barCode': 'Barcode',
      'unitsBox': 'Units x Box',
      'purchasePrice': 'Purchase Price',
      'vatIncluded': 'VAT Included',
      'margin': 'Margin',
      'salePrice': 'Sale Price',
      'currentStock': 'Current Stock',
      'safetyStock': 'Safety Stock',
      'offersActive': 'Active Offers',
      'createOffer': 'Create Offer',
      'password': 'Password',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'noAccount': "Don't have an account? Create one",
      'haveAccount': 'Already have an account? Sign in',
      'or': 'or',
      'forgotPassword': 'Forgot password?',
      'resetEmailSent': 'A password reset email has been sent to {email}',
      'sellerUnknown': 'Unknown',
      'saleNumberSN': 'Sale #: S/N',
      'customerSearchHint': 'Type to search...',
      'selectCustomerError': 'You must select a customer.',
      'netLabel': 'Net',
      'vatLabel': 'VAT',
      'paidLabel': 'Paid',
      'balanceLabel': 'Balance',
      'recordedPayments': 'Recorded Payments:',
      'loadingPayments': 'Loading payments...',
      'paymentLabel': 'Payment',
      'noteOptional': 'Note (Optional)',
      'addOneProductError': 'You must add at least one product.',
      'saleSavedSuccess': 'Sale and payment saved successfully',
      'saleUpdatedSuccess': 'Sale updated successfully',
      'saleAlreadyPaid': 'This sale is already paid.',
      'deleteOfferConfirm': 'Are you sure you want to delete this offer?',
      'saveWithoutPayment': 'Save without Payment',
      'noSales': 'No recent sales.',
      'addNewCustomer': 'Add new customer',
      'createNewProduct': 'Create new product',
      'regularPrice': 'Regular Price',
      'takingMinQty': 'Taking {qty} or more',
      'offersForProduct': 'Offers for "{product}"',
      'quantityLabel': 'Quantity',
      'salePriceIvaInc': 'Unit Price (VAT inc.)',
      'salePriceNet': 'Unit Price (Net)',
      'priceIncludesVat': 'Price includes VAT',
      'totalIvaInc': 'Total (VAT inc.)',
      'of': 'of',
      'saleDeletedSuccess': 'Sale deleted successfully',
      'noSalesRegistered': 'No sales registered.',
      'confirmDeleteSale': 'Are you sure you want to delete this sale? This action cannot be undone.',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
